# Specify a base image
FROM node:20-alpine

# Work directory
WORKDIR /usr/src/app

# Install some dependencies
COPY package.json .
RUN npm install -g @angular/cli
RUN npm install
COPY . .

# Default Command
CMD ["ng", "serve", "--host", "0.0.0.0"]
