# Specify a base image
FROM node:20-alpine

# Work directory
WORKDIR /app

# Install some dependencies
COPY package.json .
RUN npm install -g @angular/cli
RUN npm install
COPY . .

# Build 
RUN npm run build --prod

# Default Command
CMD ["ng", "serve", "--host", "0.0.0.0"]
